name: "CodeQL"

on:
    pull_request:
       branches: 
        - develop
    push:
       branches: 
        - develop
        - main
  

jobs:
  Analysis:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v4
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Analyze with SonarCloud

        uses: SonarSource/sonarcloud-github-action@master
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2  # x-release-please-version
        env:
          DEFAULT_BRANCH: develop
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
